name: simple Demo
on :
  - push

jobs:
   hello:
     runs-on: ubuntu-latest
     steps:
       - run: echo "Hello you code is pushed."


   run-test:
     runs-on: ubuntu-latest
     needs: hello
     steps:
        - uses: actions/checkout@v3
        - name: Run test.py
          run: pytest action/test.py
