name: simple Demo
on:
  - push

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello you code is pushed."

  run-test:
    runs-on: ubuntu-latest
    needs: hello
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # You can change the version if needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run pytest
        run: pytest action/test.py
